#!/usr/bin/env python
# coding: utf-8

# In[1]:


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

nba = pd.read_csv("nba_data1.csv")


# nba.head()

# In[2]:


nba.index


# In[3]:


nba.values


# In[4]:


nba.shape


# In[5]:


nba.dtypes


# In[6]:


nba.columns


# In[7]:


nba.axes


# In[8]:


nba.info()


# In[9]:


nba.dtypes.value_counts()


# In[10]:


nba.isnull().any()


# In[11]:


import pandas as pd
nba= pd.read_csv("nba_data1.csv",)
df=pd.DataFrame(nba)


# In[12]:


df1=df.dropna()


# df1

# In[13]:


del df1['Register Value']


# In[14]:


del df1['Team']


# In[ ]:





# In[15]:


import pandas as pd
nba1= pd.read_csv("nba_salary.csv",)
df=pd.DataFrame(nba1)
df2 = df


# In[ ]:





# In[16]:


df2.dtypes.value_counts()


# In[17]:


df3 = pd.concat([df1, df2], axis=1)


# In[ ]:





# In[18]:


df3.loc[df3['Full Team Name'] == 'Atlanta Hawks']


# In[19]:


df3.loc[df3['Full Team Name'] == 'Boston Celtic']


# In[20]:


df3.loc[df3['Full Team Name'] == 'Brooklyn Nets']


# In[21]:


df3.loc[df3['Full Team Name'] == 'Charlotte Hornets']


# In[22]:


df3.loc[df3['Full Team Name'] == 'Chicago Bulls']


# In[23]:


df3.loc[df3['Full Team Name'] == 'Cleveland Cavaliers']


# In[24]:


df3.loc[df3['Full Team Name'] == 'Dallas Mavericks']


# In[25]:


df3.loc[df3['Full Team Name'] == 'Denver Nuggets']


# In[26]:


df3.loc[df3['Full Team Name'] == 'Detroit Pistons']


# In[27]:


df3.loc[df3['Full Team Name'] == 'Golden State Warriors']


# In[28]:


df3.loc[df3['Full Team Name'] == 'Indiana Pacers']


# In[29]:


df3.loc[df3['Full Team Name'] == 'Los Angeles Clippers']


# In[30]:


df3.loc[df3['Full Team Name'] == 'Los Angeles Lakers']


# In[31]:


df3.loc[df3['Full Team Name'] == 'Memphis Grizzlies']


# In[32]:


df3.loc[df3['Full Team Name'] == 'Miami Heat']


# In[33]:


df3.loc[df3['Full Team Name'] == 'Milwaukee Bucks']


# In[34]:


df3.loc[df3['Full Team Name'] == 'Minnesota Timberwolves']


# In[35]:


df3.loc[df3['Full Team Name'] == 'New York Knicks']


# In[36]:


df3.loc[df3['Full Team Name'] == 'Oklahoma City Thunder']


# In[37]:


df3.loc[df3['Full Team Name'] == 'Orlando Magic']


# In[38]:


df3.loc[df3['Full Team Name'] == 'Philadelphia 76ers']


# In[39]:


df3.loc[df3['Full Team Name'] == 'Phoenix Suns']


# In[40]:


df3.loc[df3['Full Team Name'] == 'Portland Trail Blazers']


# In[41]:


df3.loc[df3['Full Team Name'] == 'Sacramento Kings']


# In[42]:


df3.loc[df3['Full Team Name'] == 'San Antonio Spurs']


# In[43]:


df3.loc[df3['Full Team Name'] == 'Toronto Raptors']


# In[44]:


df3.loc[df3['Full Team Name'] == 'Utah Jazz']


# In[45]:


df3.loc[df3['Full Team Name'] == 'Washington Wizards']


# In[46]:


df3.max()


# In[47]:


df3.min()


# In[48]:


df3.loc[df3['Player Name'] == 'LeBron James']


# In[49]:


df3.loc[df3['Player Name'] == 'Michael Jordan']


# In[50]:


df3.loc[df3['Player Name'] == 'Magic Johnson']


# In[51]:


df3.loc[df3['Player Name'] == 'Larry Bird']


# In[52]:


df3.loc[df3['Player Name'] == 'Shaquille O Neal']


# In[53]:


df3.loc[df3['Player Name'] == 'Tim Duncan']


# In[54]:


df3.loc[df3['Player Name'] == 'Kobe Bryant']


# In[55]:


df4 = df3.loc[df3['Full Team Name'] == 'Boston Celtic']


# In[56]:


df4.max()


# In[57]:


df4.min()


# In[58]:


df5 = df3.loc[df3['Full Team Name'] == 'Los Angeles Lakers']


# In[59]:


df5.max()


# In[60]:


df6 = df3.loc[df3['Full Team Name'] == 'Cleveland Caveliers']


# In[61]:


df6.max()


# In[62]:


df7 = df3.loc[df3['Full Team Name'] == 'Washington Wizards']
             


# In[63]:


df7.max()


# In[ ]:




